#!/bin/bash
plymouth=/usr/share/plymouth/themes
if ((UID != 0)); then
	echo "Please run as root or using sudo command!" && exit 1
fi
if [ ! -d $plymouth ]; then
	echo "Please install plymouth!" && exit 1
fi
if [[ $1 = -r ]]; then
  if [ -d $plymouth/simple-apple-plymouth ]; then
    echo "Wait for uninstalling complete..."
	  if type plymouth-set-default-theme 2>/dev/null; then
		  plymouth-set-default-theme -r &>/dev/null
	  else
		  update-alternatives --remove default.plymouth $plymouth/simple-apple-plymouth/simple-apple-plymouth.plymouth &>/dev/null && update-initramfs -u &>/dev/null
  	fi
	  rm -rf $plymouth/simple-apple-plymouth && echo "Uninstall success!" && exit 0
  else
	  echo "The simple-apple-plymouth theme never installed!" && exit 1
  fi
fi
echo "Please wait until installation is complete..."
cp -r simple-apple-plymouth $plymouth
if type plymouth-set-default-theme 2>/dev/null; then
	plymouth-set-default-theme -R simple-apple-plymouth &>/dev/null
else
	update-alternatives --install $plymouth/default.plymouth default.plymouth $plymouth/simple-apple-plymouth/simple-apple-plymouth.plymouth 200 &>/dev/null && update-alternatives --set default.plymouth $plymouth/simple-apple-plymouth/simple-apple-plymouth.plymouth &>/dev/null && update-initramfs -u &>/dev/null
fi
echo "The simple-apple-plymouth theme has been Configured." && exit 0
